table DimCountry
	lineageTag: 59aaa13e-08a0-4c1e-bfa5-8565ca546537

	column Country
		dataType: string
		lineageTag: 2cecb2c0-1cf8-4899-8917-76e308869ce7
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryKey
		dataType: int64
		formatString: 0
		lineageTag: 4f26ef67-18b1-4ff2-856c-eafc64003f98
		summarizeBy: none
		sourceColumn: CountryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimCountry = m
		mode: import
		queryGroup: 'Sample Tables'
		source =
				let
				    Source = _Source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Country"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "CountryKey", 1, 1, Int64.Type),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Index","United States of America","USA",Replacer.ReplaceText,{"Country"})
				in
				    #"Replaced Value"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

