table DimDiscountBand
	lineageTag: 1e3d4106-1420-4e28-aa1b-f84d7ec0f17b

	column 'Discount Band'
		dataType: string
		lineageTag: 964b5970-37ec-47b1-ba0c-6aae5eb3c5c8
		summarizeBy: none
		sourceColumn: Discount Band

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DiscountBandKey
		dataType: int64
		formatString: 0
		lineageTag: f086f4b4-8b53-4f39-adf2-abf06bd0dc63
		summarizeBy: none
		sourceColumn: DiscountBandKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimDiscountBand = m
		mode: import
		queryGroup: 'Sample Tables'
		source =
				let
				    Source = _Source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Discount Band"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "DiscountBandKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

