table DimDate
	lineageTag: 1266a7a3-473e-4d74-967f-f6af86b266e6
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: dc04e504-908f-4f4f-83df-14f17949f587
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: df55a7c1-f389-4a08-bda9-094b47ba83a5
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 4dea3b44-3e5c-41b5-8d86-9fab0479e537
		summarizeBy: none
		sourceColumn: Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 989df02d-ac28-4bda-a8a0-1661b9b22b13
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Number'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 59412fee-c68d-4782-8c44-8fef9413c06d
		summarizeBy: none
		sourceColumn: Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: aaeaf8d9-93a9-4ff4-ba31-50243ccf216d
		summarizeBy: none
		sourceColumn: Day Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 15997bed-02ca-442d-8994-96948730e84e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		queryGroup: 'Sample Tables'
		source =
				let
				    Source = _Source[Date],
				    #"Converted to Table1" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Converted to Table1",{{"Column1", Int64.Type}}),
				    DateList = #"Changed Type1"[Column1],
				    Date = {List.Min(DateList)..List.Max(DateList)},
				    #"Converted to Table" = Table.FromList(Date, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Date"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month Number", each Date.Month([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Month Name", "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Week", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted DateKey" = Table.AddColumn(#"Inserted Day Name", "DateKey", each Int64.From(Date.ToText( [Date], [ Format = "yyyyMMdd" ] )), Int64.Type )
				in
				    #"Inserted DateKey"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

