table DimSegment
	lineageTag: f8bda616-d87c-4bb6-94d4-ea8f3ece4e68

	column Segment
		dataType: string
		lineageTag: e02c3a83-7de1-4b0b-a0e5-8ef95b367592
		summarizeBy: none
		sourceColumn: Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SegmentKey
		dataType: int64
		formatString: 0
		lineageTag: 20181870-114d-49c5-8f6e-85c37ee08e20
		summarizeBy: none
		sourceColumn: SegmentKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimSegment = m
		mode: import
		queryGroup: 'Sample Tables'
		source =
				let
				    Source = _Source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Segment"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "SegmentKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

